// <auto-generated />
namespace GestionNote.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_Data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Data));
        
        string IMigrationMetadata.Id
        {
            get { return "201912111538486_add_Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
